<?php

/**
 * @file
 * Contains pw_group_icon_list.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pw_group_icon_list_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the pw_group_icon_list module.
    case 'help.page.pw_group_icon_list':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides parahraph group icon list with title and long text with reference to pw single icon list') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pw_group_icon_list_theme() {
   return [
     'paragraph__pw_group_icon_list' => [
       'base hook' => 'paragraph',
     ],
     'field__paragraph__field_pw_icon_list_reference__pw_group_icon_list' => [
       'base hook' => 'field',
     ],
  ];
}


